-- 팀 공지 메모 보드: 새 테이블 + RLS + realtime
-- Supabase 대시보드 → SQL Editor에서 이 파일 전체를 실행하세요.
-- 실행 전까지는 "팀 공지 메모" 카드가 빈 상태로만 보이고 저장은 실패합니다.

CREATE TABLE IF NOT EXISTS public.notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag text,
  content text NOT NULL,
  author text,
  color text, -- 메모 배경색 키 — src/lib/noticeColors.ts NOTICE_COLORS 참고
  status text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read notices"
ON public.notices FOR SELECT
USING (true);

CREATE POLICY "Allow public insert notices"
ON public.notices FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public update notices"
ON public.notices FOR UPDATE
USING (true);

-- 다른 탭·팀원 브라우저에 실시간 반영
ALTER PUBLICATION supabase_realtime ADD TABLE public.notices;
